server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "cdb0ea84b9bd863cbb8f54a8b4b7d70dbb081b06576122621c853ff1268c3114"